micronaut:
  application:
    name: model-crop-protocol
netty:
  default:
    allocator:
      max-order: 3
agrirouter:
  oauth:
    client-id: ${AGRIROUTER_CLIENT_ID}
    client-secret: ${AGRIROUTER_CLIENT_SECRET}
