########################################################################################################################
# Technical configuration.
########################################################################################################################
micronaut.application.name=model-crop-protocol
netty.default.allocator.max-order=3

########################################################################################################################
# URLs for the agrirouter environment.
########################################################################################################################
agrirouter.env.authorize-url=https://app.agrirouter.com/api/authorize
agrirouter.env.token-url=https://api-oauth.agrirouter.com/token
agrirouter.env.api-url=https://api.agrirouter.com

########################################################################################################################
# Agrirouter specific configuration, used to create endpoints and send messages.
########################################################################################################################
agrirouter.application-name=Model Crop Protocol
agrirouter.application-id=${AGRIROUTER_APPLICATION_ID:b0ded212-4ac9-11f1-8bc2-2639992f42ca}
agrirouter.software-version-id=${AGRIROUTER_SOFTWARE_VERSION_ID:d4136947-4ac9-11f1-8bc2-2639992f42ca}
agrirouter.software-version.capabilities=[{"message_type":"vid:wmv","direction":"SEND"},{"message_type":"vid:avi","direction":"SEND"},{"message_type":"vid:mp4","direction":"SEND"},{"message_type":"img:bmp","direction":"SEND"},{"message_type":"img:jpeg","direction":"SEND"},{"message_type":"img:png","direction":"SEND"},{"message_type":"doc:pdf","direction":"SEND"}]
agrirouter.software-version.subscriptions=[]
agrirouter.endpoint-type=cloud_software
agrirouter.oauth.client-id=${AGRIROUTER_CLIENT_ID}
agrirouter.oauth.client-secret=${AGRIROUTER_CLIENT_SECRET}

########################################################################################################################
# Application-specific configuration.
########################################################################################################################
agrirouter.oauth.redirect-uri=${AGRIROUTER_REDIRECT_URI}
persistence.storage-path=${PERSISTENCE_STORAGE_PATH:storage.json}
