micronaut.application.name=model-crop-protocol
agrirouter.oauth.client-id=${AGRIROUTER_CLIENT_ID}
agrirouter.oauth.client-secret=${AGRIROUTER_CLIENT_SECRET}
agrirouter.oauth.redirect-uri=${AGRIROUTER_REDIRECT_URI}
agrirouter.env.authorize-url=https://app.agrirouter.com/api/authorize
agrirouter.env.token-url=https://api-oauth.agrirouter.com/token
agrirouter.env.api-url=https://api.agrirouter.com
persistence.storage-path=${PERSISTENCE_STORAGE_PATH:storage.properties}